apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app-claim0
  name: app-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi