apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app-claim2
  name: app-claim2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  

