apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: npm
            - name: MYSQL_PASSWORD
              value: npm
            - name: MYSQL_ROOT_PASSWORD
              value: npm
            - name: MYSQL_USER
              value: npm
          image: jc21/mariadb-aria:10.4
          name: db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-claim0
      restartPolicy: Always
      volumes:
        - name: db-claim0
          persistentVolumeClaim:
            claimName: db-claim0

