apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-claim1
  labels:
    app: app-claim1
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/insomnio/proxymanager/app-claim1"