apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-claim0
  labels:
    app: db-claim0
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/insomnio/proxymanager/db-claim0"